### ISSUE TITLE
Relative base_path in crowdin.yaml doesn't work

### ISSUE THREAD

**Issue by vslavik** [crowdin/crowdin-cli-v1#15]
Given this `crowdin.yaml` file:

``` yaml
project_identifier: poedit
base_url: http://api.crowdin.net
base_path: .

files:
  -
    source: /locales/poedit.pot
    translation: /locales/%two_letters_code%.po
    languages_mapping:
      two_letters_code:
        ckb: ckb
        en-GB: en_GB
        pt-BR: pt_BR
        val-ES: ca@valencia
        zh-CN: zh_CN
        zh-TW: zh_TW
```

Uploading the translations with `crowdin-cli  upload translations --auto-approve-imported --import-eq-suggestions` (_after_ uploading the POT file first) fails with 

```
Warning: Skip `/locales/cs.po'
```

etc. After a while, I realized the problem is in the `base_path`. If I omit it (which has the same effect, because pwd is the default), it works. But then, I get the annoying _Configuration file misses parameter `base_path` that defines your project root directory_ warning on every invocation. 

Using an _absolute_ path as `base_path` takes care of both, but that's not usable in practice: I cannot commit absolute path to the (public) repository, because different people may have it checked out in different locations (even I alone have different checkouts with different paths).

Not sure where this difference between `.` and absolute pwd comes from, perhaps the tool should absolutize any relative `base_path` first?
