### ISSUE TITLE
Support mask for 'dest' in config file.

### ISSUE THREAD

**Issue by gonimar** [crowdin/crowdin-cli-v1#23]
Example:

``` yaml
files:
  -
    source: '/path/to/*.properties'
    translation: '/path/%two_letters_code%/%two_letters_code%'
// 
    dest: '/path/in/crowdin/*.properties'
// or
    dest: '/path/in/crowdin/%original_file_name%'
```
