### ISSUE TITLE
Download with languages_mapping (locale to two_letters_code)

### ISSUE THREAD

**Issue by GreatWizard** [crowdin/crowdin-cli-v1#25]
Hello,

I have a little issue to download files with languages_mapping from `%locale%` to `%two_letters_code%`.

I'm not sure this is an issue or voluntary on your part.

This i my config file:

```
files:
  -
    source: 'en/file.json'
    translation: '%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        # crowdin_language_code: custom_code
        'es-ES': 'es'

```

What happened when I start download:

```
Build ZIP archive with the latest translations - Skipped
Warning: Export was skipped. Please note that this method can be invoked only once per 30 minutes.
Download: `nl/file.json'
Download: `fr/file.json'
Warning: Downloaded translations do not match current project configuration. Some of the resulted files will be omitted.
 - `es-ES/file.json'
```

**Comment by mamantoha** [comment]
Hello. Try again in 30 minutes. Maybe the problem is that you did `download` before you add `languages_mapping` in the config file.

**Comment by GreatWizard** [comment]
I can confirm that didn't work as expected, I have checked the config before `download` and retry now without success.

**Comment by mamantoha** [comment]
I don't understand what's going on here.
You can define the path for files in resulting archive by putting the slash (/) at the beginning of the pattern.

```
files:
  -
    source: '/en/file.json'
    translation: '/%two_letters_code%/%original_file_name%'
```

**Comment by GreatWizard** [comment]
My config file here doesn't work:

```
base_path: ./app/locales/

files:
  -
    source: 'en/file.json'
    translation: '/%two_letters_code%/%original_file_name%'
    languages_mapping:
      two_letters_code:
        'es-ES': 'es'
```

My translation file look like:

```
{
  "general":{
    "yes":"Yes",
    "no":"No",
    "cancel":"Cancel"
  }
}
```

It's the same with ou without the slash.
Do you manage to reproduce it on your computer?
