### ISSUE TITLE
languages_mapping not properly working?

### ISSUE THREAD

**Issue by tobiasschuerg** [crowdin/crowdin-cli-v1#43]
I use this mapping:

``` yaml
    languages_mapping:
      android_code:
        af: af
        ar: ar
        be: be
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        es: es
        et: et
        fi: fi
        fr: fr
        gl: gl
        iw: iw
        hi: hi
        hr: hr
        hu: hu
        in: in
        it: it
        iw: iw
        ja: ja
        ko: ko
        lt: lt
        nl: nl
        no: no
        pl: pl
        ro: ro
        ru: ru
        sk: sk
        sl: sl
        sr: sr
        sv: sv
        tr: tr
        uk: uk
        vi: vi
```

But receive this:

![image](https://cloud.githubusercontent.com/assets/1324555/13384587/b3ca1ffe-de75-11e5-86b0-1d356711fd52.png)

**why is for example es not properly mapped although mapping is given?**

**Comment by mamantoha** [comment]
There are no language code `es`. You can use `es-ES`.
See available languages codes here: https://crowdin.com/page/api/language-codes

**Comment by tobiasschuerg** [comment]
Ah, didn't see that list ;-)
Thank you!

**Comment by tobiasschuerg** [comment]
Ther is one left, for which I don't get the mapping to work: **norwegian**

> Extracting: `values-no-rNO/strings.xml'

Although I tried :

`no: no`

and also each of:

``` yaml
  nb:no
  nn-NO: no
  no-No: no
```
