### ISSUE TITLE
crowdin-cli upload sources hangs because "files are uploaded but not imported"

### ISSUE THREAD

**Issue by adepablor** [crowdin/crowdin-cli-v1#46]
Hi guys,

Already submitted this through support but I guess it would gurt to do it here.

When trying to upload sources for a branch via `crowdin-cli upload sources -b branch_name` the scripts hangs and we see this error in the crowdin UI. Only way to solve it is to hit import for all the files.....

<img width="1207" alt="screen shot 2016-04-20 at 1 53 41 pm" src="https://cloud.githubusercontent.com/assets/964907/14684829/c359906e-06ff-11e6-8e0e-65b06c07401e.png">

**Comment by mamantoha** [comment]
Hi, @adepablor .

Can you provide your config file w/o credentials?

**Comment by adepablor** [comment]
Yep

``` yaml
files:
  -
    source: '/web/WEB-INF/localization/en/*.properties'
    translation: '/web/WEB-INF/localization/%locale%/%original_file_name%'
    escape_quotes: 1
    ignore:
      - '/web/WEB-INF/localization/en/foreign_license_instructions.properties'
    languages_mapping:
      locale:
        'fr-CA': 'fr'
  -
    source: '/web/resources/js/locales/en.json'
    translation: '/web/resources/js/locales/%locale%.%file_extension%'
    languages_mapping:
      locale:
        'fr-CA': 'fr'
```
