### ISSUE TITLE
How to deal with translation-files that have the locale in the filename?

### ISSUE THREAD

**Issue by leberknecht** [crowdin/crowdin-cli-v1#50]
Hi!

Unfortunately we dont have a 

```
translations/
    en/somefile.xlf
    de/somefile.xlf
```

structure, but instead we have the locale on the filenames, like this:

```
translations/
    somefile.en.xlf
    somefile.de.xlf
```

Is there any way how i can configure `source` and `translation` on the corwdin.yaml so this will work?

**Comment by mamantoha** [comment]
Hi.
You can use something like this:

```
files:
  -
    source: '/translations/somefile1.en.xlf'
    translation: '/translations/somefile1.%two_letters_code%.xlf'
  -
    source: '/translations/somefile2.en.xlf'
    translation: '/translations/somefile2.%two_letters_code%.xlf'
```
