### ISSUE TITLE
Slowness on Ubuntu 14.04 - Ruby 2.3.0

### ISSUE THREAD

**Issue by lucasff** [crowdin/crowdin-cli-v1#54]
Just installed RVM with Ruby 2.3.0 and the only gem installed is crowdin-cli.
After running crowdin-cli download sources for example, it takes around 10 minutes to complete the operation. Using strace, I can see the whole directory is being scanned even if the configuration YAML file tells which path to look for translations.

Very simple crowdin.yaml file:

```
files:
  -
    source: /resources/lang/default/*.php
    translation: /resources/lang/%two_letters_code%/%original_file_name%
```
