### ISSUE TITLE
Pluralized strings removed in chinese translations

### ISSUE THREAD

**Issue by mbuffa** [crowdin/crowdin-cli-v1#59]
Hey,
When I download translations from my crowdin project using crowdin-cli, pluralized keys used by rails-18n are missing, resulting in a tree like this:
```yml
users:
   one: "1 user" # this one is missing
   other: "%{count} users"
```
This is an issue because rails-i18n can't fallback on 'other'. I'm using `preverse_hierarchy: true`.
It may be nice to be able to replicate 'other' values as 'one' to avoid breakages.

**Comment by mamantoha** [comment]
Hi.
Can you show an example of the source file?

**Comment by mbuffa** [comment]
OP already got a sample, but here's an actual extract:
```yml
en-US:
  shared:
    # Filter & Sort
    filter_and_sort:
      filter_btn:
        one: "1 active filter"
        other: "%{count} active filters"
```
When translating into zh-CN and downloading translations, `one` entry is removed:
```yml
zh-CN:
  shared:
    filter_and_sort:
      filter_btn:
        other: "%{count} 个有效筛选"
```
Moving up the `other` value to `filter_btn` may fix this.
