### ISSUE TITLE
Language mapping not working

### ISSUE THREAD

**Issue by thomasjoulin** [crowdin/crowdin-cli-v1#61]
It used to work, I'm not sure what changed since. My yaml file (iOS project):

```yaml
project_identifier: REDACTED
api_key: REDACTED
base_path: .
files:
- source: "/Resources/en.lproj/*"
  translation: "/Resources/%osx_code%/%original_file_name%"
  languages_mapping:
    osx_code:
      es-MX: es.lproj
      pt-BR: pt.lproj
      zh-CN: zh-Hans.lproj
      zh-TW: zh-Hant.lproj
```

My files on crowdin are set to be exported following this format: `/Resources/%osx_code%/%original_file_name%`

All languages without mapping (like `en`) are put in their correct place. Languages with mapping (like `es-MX`) are not. I get an error like this:

```sh
$> crowdin-cli download
...
Warning: Downloaded translations do not match current project configuration. The following files will be omitted:
 - `Resources/zh-Hans.lproj/Localizable.strings'
 - `Resources/zh-Hans.lproj/Localizable.stringsdict'
 - `Resources/zh-Hans.lproj/InfoPlist.strings'
 - `Resources/zh-Hant.lproj/Localizable.strings'
 - `Resources/zh-Hant.lproj/Localizable.stringsdict'
 - `Resources/zh-Hant.lproj/InfoPlist.strings'
 - `Resources/pt-BR.lproj/Localizable.strings'
 - `Resources/pt-BR.lproj/Localizable.stringsdict'
 - `Resources/pt-BR.lproj/InfoPlist.strings'
 - `Resources/es-MX.lproj/Localizable.strings'
 - `Resources/es-MX.lproj/Localizable.stringsdict'
 - `Resources/es-MX.lproj/InfoPlist.strings'
... // other branches shows too like - `branch-name/Resources/pt-BR.lproj/InfoPlist.strings'
```

My local project file structure looks like this:

![screen shot 2018-01-31 at 10 57 18 am](https://user-images.githubusercontent.com/52842/35602903-b053f190-0675-11e8-8a9f-683346379a26.png)

If I build and download from Crowdin website the structure looks like this:

![screen shot 2018-01-31 at 10 59 16 am](https://user-images.githubusercontent.com/52842/35602924-cc84dde8-0675-11e8-93e7-1be455c16147.png)

Wondering if it's due to branches, in my example I do `crowdin-cli download` without branch param
