### ISSUE TITLE
Using locale or two letter code based on project

### ISSUE THREAD

**Issue by amura11** [crowdin/crowdin-cli-v1#65]
I have a project in Crowdin that's being translated into French (fr), Spanish Mexico (es-MX), and Spanish Spain (es-ES). I'm running into an issue where if I defined my configuration to use `%locale%` the translations for French have `fr-FR` in the name (which causes C# to fallback if the locale is `fr-CA` for example) but if I use `%two_letters_code%` I only get files with `es` in the name. If I manually download the files they have the correct codes (fr, es-MX, and es-ES).

Is there anyway to setup my configuration so my files download using either the two letter code or the full locale based on the project?

**Comment by mamantoha** [comment]
Hi @amura11 
Yes, you can use [Languages mapping](https://github.com/crowdin/crowdin-cli#languages-mapping).

I think something like this should help you:

```yaml
files:
  -
    source: [...]
    translation: [...]
    languages_mapping:
      locale:
        # crowdin_language_code: local_name
        fr: fr
```
