### ISSUE TITLE
Invalid android langauges codes

### ISSUE THREAD

**Issue by rosenpin** [crowdin/crowdin-cli-v1#69]
This is my  crowdin yml configuration:
``` yaml
project_identifier: ....
api_key: ...
base_path: ...

files:
  -
    source: '/app/src/main/res/values/strings.xml'
    translation: '/app/src/main/res/values-%android_code%/%original_file_name%'
    translate_attributes: '0'
``` 

This is my website configuration:
![image](https://user-images.githubusercontent.com/5289630/51788293-fcab5f80-2184-11e9-9165-ccdeae2d4b7d.png)

After running `java -jar crowdin-cli.jar download`
all the files are downloaded in the following format:
![image](https://user-images.githubusercontent.com/5289630/51788301-2c5a6780-2185-11e9-955c-eecd1944816a.png)

But when trying to compile the project I get the following error: 
```diff
- app/src/main/res/values-kab-rKAB: Error: Invalid resource directory name
```
It seems like some of the language codes are incorrect and cause compilation errors.

When I use the 2 letters code it works, but it causes me to loose some of the translation languages.

Is this a known error and is there a solution?
